name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.caprohit }}
          password: ${{ secrets.Narutoog@1007 }}

      - name: Build Docker image
        run: docker build -t yourusername/hello-world:latest .

      - name: Push Docker image
        run: docker push yourusername/hello-world:latest
